#!/bin/bash

set -eufo pipefail

for c in curl git; do
    if ! command -v $c >/dev/null 2>&1; then
        >&2 echo "$c not available..."
        exit 1
    fi
done

if ! ssh -T git@github.com 2>&1 | grep yerejm >/dev/null 2>&1; then
    >&2 echo "No ssh access to github..."
    exit 1
fi

chezmoi=chezmoi
if [ ! "$(command -v $chezmoi)" ]; then
    bin_dir="$HOME/.local/bin"
    chezmoi="$bin_dir/chezmoi"
    sh -c "$(curl -fsSL https://git.io/chezmoi)" -- -b "$bin_dir"
fi

exec "$chezmoi" init --apply --ssh github.com/yerejm/home
